# Homework Set 2

Please **submit this Jupyter notebook through Canvas** no later than **Mon Nov. 15, 9:00**.

Homework is in **groups of two**, and you are expected to hand in original work. Work that is copied from another group will not be accepted.

# Exercise 0
Write down the names + student ID of the people in your group.

$
Julius Wantenaar \\11339055\\
Sebastiaan Bye
$

Run the following cell to import the necessary packages.

In [1]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
import random

# Exercise 1

The goal of this problem is to show that apparently harmless looking systems of linear equations may be very difficult to solve. Some functions that may be useful are `numpy.triu`, `numpy.tril`, `numpy.eye`, `random.randrange`.
## (a)
Generate an $n \times n$ matrix $B$ with random integer elements in the range
$b_{ij} \in [-10, 10]$. Choose for instance $n=20$.


In [59]:
n = 2
B = np.rint(np.random.rand(n,n)*20 - 10)

## (b)
Remove the diagonal of $B$, save the upper triangular part in $U$ and the lower triangular part in $L$, and put ones on the diagonals $l_{ii} = u_{ii} = 1$.

In [60]:
L = np.zeros((n,n))
U = np.zeros((n,n))
for row in range(n):
    for column in range(n):
        if row == column:
            # diagonal
            B[row][column] = 1
        
for row in range(n):
    for column in range(n):        
        if row < column:
            # lower
            L[row][column] = B[row][column]
        elif row > column:
            #upper
            U[row][column] = B[row][column]
        
np.fill_diagonal(L, 1)
np.fill_diagonal(U, 1)

1.0

## (c)
Compute $A = L \cdot U$. What is the value of $\det(A)$ and why? Compute the determinant using the appropriate python command and confirm your prediction. In case that you have doubts about the result, compute separately $\det(L)$ and $\det(U)$.

In [84]:
A = np.matmul(L,U)
np.linalg.det(A)

0.9999999999999964

In [62]:
np.linalg.slogdet(A)

(1.0, -3.552713678800501e-15)

1 because the diagonal is 1


## (d)
Choose now an exact solution, for instance $x_{\rm e} =$ `numpy.ones(n)`, and compute the corresponding right hand side $b = A x_{\rm e}$.


In [63]:
b = np.matmul(A, np.ones(n))

b

array([-29.,  -6.])

## (e)
Solve $A x = b$ using `scipy.linalg.lu_factor` and `scipy.linalg.lu_solve` and compare the solution with the exact $x_{\rm e}$. 

In [86]:
lu, piv = la.lu_factor(A)
la.solve((lu,piv), b)

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


ValueError: ignored

array([[-3.40000000e+01,  5.00000000e+00],
       [ 2.05882353e-01, -2.94117647e-02]])

In [80]:
from scipy.linalg import lu_factor, lu_solve
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
b = np.array([1, 1, 1, 1])
lu2, piv2 = lu_factor(A)
x = lu_solve((lu2, piv2), b)
#np.allclose(A @ x - b, np.zeros((4,)))
x

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [81]:
lu2

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.28571429,  3.57142857,  6.28571429,  5.28571429],
       [ 0.71428571,  0.12      , -1.04      ,  3.08      ],
       [ 0.71428571, -0.44      , -0.46153846,  7.46153846]])

## (f)
Explain the bad results by computing the condition number of $A$.

In [90]:
np.linalg.cond(A)

1230.9991876517854

It is very high, making it very sensitive to errors.


# Exercise 2

(N.B. this is a theory exercise.)
Suppose we write a $(p+q) \times (p+q)$ matrix $M$ in block form where
$A, B, C, D$ are respectively $p \times p, p \times q, q \times p$
and $q \times q$ matrices
$$ M = \begin{bmatrix} A & B \\ C & D  \end{bmatrix}. $$

## (a)
Verify that 
$   \begin{bmatrix} A & B \\ C & D 
    \end{bmatrix} =
    \begin{bmatrix} I_p & 0 \\ C A^{-1} & I_q 
    \end{bmatrix}
    \begin{bmatrix} A & 0\\ 0 & D - CA^{-1} B
    \end{bmatrix}
    \begin{bmatrix} I_p & A^{-1} B \\ 0 & I_q 
    \end{bmatrix} 
$

$   \begin{bmatrix} I_p & 0 \\ C A^{-1} & I_q 
    \end{bmatrix}
    \begin{bmatrix} A & 0\\ 0 & D - CA^{-1} B
    \end{bmatrix}
    =
    \begin{bmatrix} (I_{P}*A) + (0*0) & (I_{p} * 0) + (0* D-CA^{-1}B) \\ (CA^{-1}*A) + (I_{p}*0) & (CA^{-1}*0)+(I_{p}*D-CA^{-1}B)
    \end{bmatrix}
    =
    \begin{bmatrix} A & 0 \\ C & D-CA^{-1}B
    \end{bmatrix}
$

The second step
$
    \begin{bmatrix} A & 0 \\ C & D-CA^{-1}B
    \end{bmatrix}
    \begin{bmatrix} I_p & A^{-1} B \\ 0 & I_q 
    \end{bmatrix}
    =
    \begin{bmatrix} (A*I_{p}) + 0*0 & (A*A^{-1}B) + (0*I_{p}) \\ (C*I_{p})+(0*(D-CA^{-1}B)) & (C*A^{-1}B) + (D-CA^{-1}B*I_{p})
    \end{bmatrix}
$

## (b)
Describe how a system $M x = b$, with $x$ and $b$ in $\mathbb{R}^{p+q}$,
can be solved by applying matrix-vector products with $C$ and
$B$ and solves with $A$ and $(D - CA^{-1}B)$.

Write your answer, using $\LaTeX$, in this box.

## (c)
What is the cost, to highest order, of LU-factorizing $A$ and of
computing and LU-factorizing $D - CA^{-1} B$? 

Write your answer, using $\LaTeX$, in this box.

**Remark**: Although in this case no savings were obtained, the decomposition
above is very useful for solving linear systems with many zero coefficients,
in other words where $M$ is a sparse matrix. After applying a
permutation of the indices such a matrix is written in the above
form, where $q$ is as small as possible and $A$ is blockdiagonal,
i.e. $A = \begin{bmatrix} E & O \\ O & F \end{bmatrix}$. This
blockdiagonal form then causes big savings in computational
cost. Moreover, the procedure can be applied recursively to $E$ and $F$.